<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>EnvisionSuite.Core</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AssemblyName>EnvisionSuiteCore</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <DirectPInvoke Include="libc"/>
  </ItemGroup>

</Project>
